/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import ui.Popup;
import ui.PopupLoading;

/**
 *
 * @author Go
 */
public class LoginPage extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setLocationRelativeTo(null);
        jLabel1.requestFocus();
        passTxt.setText("Mot de passe");
        passTxt.setEchoChar((char)0);
        passTxt.setForeground(new Color(187, 187, 187));
        
    }
    
    protected ImageIcon createImageIcon(String path) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        loginTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        passTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(31, 58, 105));
        loginPanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\users\\gmultari\\Desktop\\projet_SIS\\src\\ui\\images\\login_left.png")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\users\\gmultari\\Desktop\\projet_SIS\\src\\ui\\images\\logo.png")); // NOI18N

        loginTxt.setBackground(new java.awt.Color(255, 255, 255));
        loginTxt.setFont(new java.awt.Font("Ebrima", 1, 15)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(187, 185, 187));
        loginTxt.setText("Identifiant");
        loginTxt.setToolTipText("Identifiant");
        loginTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(31, 58, 105)));
        loginTxt.setSelectedTextColor(new java.awt.Color(137, 137, 137));
        loginTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginTxtFocusLost(evt);
            }
        });
        loginTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTxtActionPerformed(evt);
            }
        });
        loginTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loginTxtKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(31, 58, 105));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SE CONNECTER");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        passTxt.setBackground(new java.awt.Color(255, 255, 255));
        passTxt.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        passTxt.setForeground(new java.awt.Color(187, 185, 187));
        passTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(31, 58, 105)));
        passTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passTxt.setPreferredSize(new java.awt.Dimension(74, 22));
        passTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passTxtFocusLost(evt);
            }
        });
        passTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(loginTxt)
                    .addComponent(passTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginTxt.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1318, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void setPlaceHolder(JTextField txt, String text){
        txt.setForeground(new Color(187, 187, 187));
        txt.setText(text);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = this.loginTxt.getText();
        String pass = String.valueOf(this.passTxt.getPassword());
        
        if(id.length() > 2){
            startRequestThread(id, pass);
        } else {
            Popup.createPopupMdpIncorrect();
        }
//        switch(text){
//            case "1":
//                java.awt.EventQueue.invokeLater(new Runnable() {
//                    public void run() {
//                        new SecretaireMedPage().setVisible(true);
//                    }
//                });
//                this.dispose();
//                break;
//            case "2":
//                java.awt.EventQueue.invokeLater(new Runnable() {
//                    public void run() {
//                        new SecretaireAdminPage().setVisible(true);
//                    }
//                });
//                this.dispose();
//                break;
//            case "3":
//                this.dispose();
//                break;
//                
//        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void startRequestThread(String id, String pass){
        JFrame popup = new PopupLoading();
        SwingWorker sw = new SwingWorker(){
            @Override
            protected String doInBackground() throws Exception 
            {
                jButton1.setEnabled(false);
                popup.setVisible(true);
                String res;
                try{
                    if(bdd.ConnectBD.login(id, pass)){
                        
                    } else {
                        Popup.createPopupMdpIncorrect();
                    }
                } catch (Exception e){
                    Popup.createPopupErreurConnexion();
                }

                return null;
            }
  
  
            @Override
            protected void done() 
            {
                jButton1.setEnabled(true);
                popup.setVisible(false);
            }
        };
          
        // executes the swingworker on worker thread
        sw.execute(); 
        
        
    }
    private void loginTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginTxtFocusGained
        
        if(loginTxt.getText().equals("Identifiant")){
            loginTxt.setText("");
            loginTxt.setForeground(new Color(137, 137, 137));
        }
    }//GEN-LAST:event_loginTxtFocusGained

    private void loginTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTxtActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_loginTxtActionPerformed

    private void loginTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginTxtFocusLost
        if(this.loginTxt.getText().equals("")){
            this.loginTxt.setForeground(new Color(187, 187, 187));
            this.loginTxt.setText("Identifiant");
        }
    }//GEN-LAST:event_loginTxtFocusLost

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_passTxtActionPerformed

    private void passTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTxtFocusLost
    String password = String.valueOf(passTxt.getPassword());
    if(password.toLowerCase().equals("") )
    {
        passTxt.setText("Mot de passe");
        passTxt.setEchoChar((char)0);
        passTxt.setForeground(new Color(187, 187, 187));
    }
    }//GEN-LAST:event_passTxtFocusLost

    private void passTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passTxtFocusGained
     
        passTxt.setEchoChar('\u26AB');
        String password = String.valueOf(passTxt.getPassword());

        if(password.toLowerCase().equals("mot de passe"))
        {
            passTxt.setText("");
            passTxt.setForeground(new Color(137, 137, 137));
        }
    }//GEN-LAST:event_passTxtFocusGained

    private void loginTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginTxtKeyTyped
        char c = evt.getKeyChar();
        if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
             evt.consume();  // ignorer l'événement
        }
    }//GEN-LAST:event_loginTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JPasswordField passTxt;
    // End of variables declaration//GEN-END:variables
}
