/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import fc.Date;
import fc.Prescription;
import fc.TextValidator;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author Go
 */
public class PopupAjoutPrescription extends javax.swing.JFrame {
    AjoutVisitePage main = null;
    Prescription prescription; 
    /**
     * Creates new form PopupCreationPatientReussite
     */
    public PopupAjoutPrescription() {
        
//        this.setContentPane(new RoundedPanel());
        initComponents();
        setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        lblErreur.setVisible(false);
        this.pack();
    }
    
     public PopupAjoutPrescription(AjoutVisitePage main) {
        
        this.main = main;
        initComponents();
        setLocationRelativeTo(null);
        lblErreur.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fldMoisDebut = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fldAnneeDebut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fldJourDebut = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fldJourFin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fldMoisFin = new javax.swing.JTextField();
        fldAnneeFin = new javax.swing.JTextField();
        fldMedicament = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fldPosologie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fldDose = new javax.swing.JTextField();
        lblErreur = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 58, 105), 2, true));

        jButton1.setBackground(new java.awt.Color(31, 58, 105));
        jButton1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AJOUTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(31, 58, 105));
        jButton2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ANNULER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 58, 105));
        jLabel7.setText("/");

        fldMoisDebut.setBackground(new java.awt.Color(255, 255, 255));
        fldMoisDebut.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldMoisDebut.setForeground(new java.awt.Color(116, 116, 116));
        fldMoisDebut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(31, 58, 105)));
        fldMoisDebut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldMoisDebutKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 58, 105));
        jLabel8.setText("/");

        fldAnneeDebut.setBackground(new java.awt.Color(255, 255, 255));
        fldAnneeDebut.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldAnneeDebut.setForeground(new java.awt.Color(116, 116, 116));
        fldAnneeDebut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(31, 58, 105)));
        fldAnneeDebut.setMaximumSize(new java.awt.Dimension(0, 28));
        fldAnneeDebut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldAnneeDebutKeyTyped(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 58, 105));
        jLabel2.setText("Du :");

        fldJourDebut.setBackground(new java.awt.Color(255, 255, 255));
        fldJourDebut.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldJourDebut.setForeground(new java.awt.Color(116, 116, 116));
        fldJourDebut.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(31, 58, 105)));
        fldJourDebut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldJourDebutKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 58, 105));
        jLabel9.setText("/");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 58, 105));
        jLabel3.setText("Au :");

        fldJourFin.setBackground(new java.awt.Color(255, 255, 255));
        fldJourFin.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldJourFin.setForeground(new java.awt.Color(116, 116, 116));
        fldJourFin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(31, 58, 105)));
        fldJourFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldJourFinKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 58, 105));
        jLabel10.setText("/");

        fldMoisFin.setBackground(new java.awt.Color(255, 255, 255));
        fldMoisFin.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldMoisFin.setForeground(new java.awt.Color(116, 116, 116));
        fldMoisFin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(31, 58, 105)));
        fldMoisFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldMoisFinKeyTyped(evt);
            }
        });

        fldAnneeFin.setBackground(new java.awt.Color(255, 255, 255));
        fldAnneeFin.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldAnneeFin.setForeground(new java.awt.Color(116, 116, 116));
        fldAnneeFin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(31, 58, 105)));
        fldAnneeFin.setMaximumSize(new java.awt.Dimension(0, 28));
        fldAnneeFin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldAnneeFinKeyTyped(evt);
            }
        });

        fldMedicament.setBackground(new java.awt.Color(255, 255, 255));
        fldMedicament.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldMedicament.setForeground(new java.awt.Color(116, 116, 116));
        fldMedicament.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 28, 105), 2, true));
        fldMedicament.setMargin(new java.awt.Insets(5, 5, 5, 5));
        fldMedicament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldMedicamentActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 58, 105));
        jLabel4.setText("Médicament :");

        fldPosologie.setBackground(new java.awt.Color(255, 255, 255));
        fldPosologie.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldPosologie.setForeground(new java.awt.Color(116, 116, 116));
        fldPosologie.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 28, 105), 2, true));
        fldPosologie.setMargin(new java.awt.Insets(5, 5, 5, 5));
        fldPosologie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldPosologieActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 58, 105));
        jLabel5.setText("Posologie :");

        fldDose.setBackground(new java.awt.Color(255, 255, 255));
        fldDose.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        fldDose.setForeground(new java.awt.Color(116, 116, 116));
        fldDose.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 28, 105), 2, true));
        fldDose.setMargin(new java.awt.Insets(5, 5, 5, 5));
        fldDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldDoseActionPerformed(evt);
            }
        });

        lblErreur.setBackground(new java.awt.Color(255, 255, 255));
        lblErreur.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblErreur.setForeground(new java.awt.Color(255, 51, 51));
        lblErreur.setText("Veuillez compléter l'intégralité des champs.");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 58, 105));
        jLabel11.setText("Dose :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldDose, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldPosologie)))
                .addGap(0, 110, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblErreur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldJourDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldMoisDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldAnneeDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldJourFin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldMoisFin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fldAnneeFin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(fldDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldPosologie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fldJourDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(fldMoisDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(fldAnneeDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(fldJourFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(fldMoisFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(fldAnneeFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErreur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(TextValidator.allFieldsAreFilled(jPanel1)){
            String medicament = this.fldMedicament.getText();
            String dose = this.fldDose.getText();
            String posologie = this.fldPosologie.getText();

            Date dateDebut = new Date( fldJourDebut.getText(), fldMoisDebut.getText(), fldAnneeDebut.getText() );
            Date dateFin = new Date( fldJourFin.getText(), fldMoisFin.getText(), fldAnneeFin.getText() );
            prescription = new Prescription(medicament, dose, posologie, dateDebut, dateFin);
            main.addPrescription(prescription);
            this.dispose();
        } else {
            this.lblErreur.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fldJourDebutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldJourDebutKeyTyped
        TextValidator.consumeNonIntegers(evt, 2, 31);
    }//GEN-LAST:event_fldJourDebutKeyTyped

    private void fldJourFinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldJourFinKeyTyped
        TextValidator.consumeNonIntegers(evt, 2, 31);
    }//GEN-LAST:event_fldJourFinKeyTyped

    private void fldMedicamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldMedicamentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldMedicamentActionPerformed

    private void fldPosologieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldPosologieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldPosologieActionPerformed

    private void fldDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldDoseActionPerformed

    private void fldMoisDebutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldMoisDebutKeyTyped
        TextValidator.consumeNonIntegers(evt, 2, 12);
    }//GEN-LAST:event_fldMoisDebutKeyTyped

    private void fldAnneeDebutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldAnneeDebutKeyTyped
        TextValidator.consumeNonIntegers(evt, 4, 9999);
    }//GEN-LAST:event_fldAnneeDebutKeyTyped

    private void fldMoisFinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldMoisFinKeyTyped
        TextValidator.consumeNonIntegers(evt, 2, 12);
    }//GEN-LAST:event_fldMoisFinKeyTyped

    private void fldAnneeFinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldAnneeFinKeyTyped
        TextValidator.consumeNonIntegers(evt, 4, 9999);
    }//GEN-LAST:event_fldAnneeFinKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupAjoutPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupAjoutPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupAjoutPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupAjoutPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupAjoutPrescription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fldAnneeDebut;
    private javax.swing.JTextField fldAnneeFin;
    private javax.swing.JTextField fldDose;
    private javax.swing.JTextField fldJourDebut;
    private javax.swing.JTextField fldJourFin;
    private javax.swing.JTextField fldMedicament;
    private javax.swing.JTextField fldMoisDebut;
    private javax.swing.JTextField fldMoisFin;
    private javax.swing.JTextField fldPosologie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErreur;
    // End of variables declaration//GEN-END:variables
}
