/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bdd.ConnectBD;
import fc.Visite;
import fc.Patient;
import fc.Personnel;
import fc.Prescription;
import fc.Prestation;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author Go
 */
public class VisitePage extends javax.swing.JFrame {
    private final String idDM = "1";
    private final String ipp = "123456";
    private Visite visite;
    private Patient patient;
    /**
     * Creates new form SecretaireAdminPage
     */
    public VisitePage() {
        initComponents();
        setLocationRelativeTo(null);
        
        initLabelsAndTables();
    }
    
    public final void initLabelsAndTables(){
        JFrame popup = new PopupLoading();
        popup.setVisible(true);
        
        fc.Look.setTableLook(prescriptionTable);
        fc.Look.setTableLook(prestationTable);
        fc.Look.setScrollBar(scrollPane);
        fc.Look.setScrollBar(scrollPaneObs);
        fc.Look.setScrollBar(scrollPanePrescription);
        fc.Look.setScrollBar(scrollPanePrestation);
        
        SwingWorker sw = new SwingWorker(){
            @Override
            protected String doInBackground() throws Exception 
            {
                try{
                    visite = ConnectBD.getVisiteByIdDm(idDM);
                    patient = ConnectBD.getPatientByIPP(ipp);
                } catch (Exception e){
                    System.err.println(e.getMessage());
                    PopupFactory.createPopupErreurConnexion();
                }
                fillPrescriptionTable();
                fillPrestationTable();
                fillLabels();
                return "";
            }
  
            @Override
            protected void done() 
            {
                popup.setVisible(false);
            }
        };
          
        // executes the swingworker on worker thread
        sw.execute(); 
    }
    
    private void fillPrescriptionTable(){
        String headers[] = {"Medicament", "Dosage", "Posologie", "Debut", "Fin"};
        DefaultTableModel model = new DefaultTableModel(null, headers);
        for(Prescription c : visite.getPrescriptions()){
            model.addRow(c.getPrescriptionForTable());
        }
        this.prescriptionTable.setModel(model);
    }
    
    private void fillPrestationTable(){
        String headers[] = {"Prestation", "Service"};
        DefaultTableModel model = new DefaultTableModel(null, headers);
        
        for(Prestation c : visite.getPrestations()){
            model.addRow(c.getPrestationForTable());
        }
        this.prestationTable.setModel(model);
    }
    
    public void fillLabels(){
       
        this.dateNaissanceLbl.setText( patient.getDateDeNaissance().toString());
        this.nomPatientLbl.setText( patient.getNom() );
        this.prenomPatientLbl.setText( patient.getPrenom() );
        this.sexeLbl.setText( patient.getSexe().getVal() );
        
        this.lblDateConsultation.setText( visite.getDateEntree().toString() );
        this.lblHeureConsultation.setText( visite.getDateEntree().getHeureMinute());
        this.lblNomPraticien.setText( visite.getNomPh() );
        this.lblMotif.setText( visite.getMotif() );
        this.txtObservations.setText( visite.getObservation() );
        
        this.lblTypeVisite.setText( visite.getType() );
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        profilePictLb = new javax.swing.JButton();
        serviceLb = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        disconnectBtn = new javax.swing.JButton();
        portalLb = new javax.swing.JLabel();
        profilePictLb1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomPatientLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prenomPatientLbl = new javax.swing.JLabel();
        sexeLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateNaissanceLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        lblTypeVisite = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        profilePictLb3 = new javax.swing.JButton();
        lblDateConsultation = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblNomPraticien = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblMotif = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        profilePictLb4 = new javax.swing.JButton();
        scrollPaneObs = new javax.swing.JScrollPane();
        txtObservations = new javax.swing.JTextArea();
        profilePictLb5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        profilePictLb6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        scrollPanePrescription = new javax.swing.JScrollPane();
        prescriptionTable = new javax.swing.JTable();
        scrollPanePrestation = new javax.swing.JScrollPane();
        prestationTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        lblHeureConsultation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(31, 58, 105));

        jPanel2.setBackground(new java.awt.Color(34, 170, 224));

        profilePictLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/profile_placeholder.png"))); // NOI18N
        profilePictLb.setBorder(null);
        profilePictLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePictLbMouseEntered(evt);
            }
        });
        profilePictLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePictLbActionPerformed(evt);
            }
        });

        serviceLb.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        serviceLb.setForeground(new java.awt.Color(255, 255, 255));
        serviceLb.setText("Service");

        nameLb.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        nameLb.setForeground(new java.awt.Color(255, 255, 255));
        nameLb.setText("NOM Prénom");

        disconnectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/disconnect.png"))); // NOI18N
        disconnectBtn.setBorder(null);
        disconnectBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                disconnectBtnMouseEntered(evt);
            }
        });
        disconnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(profilePictLb)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nameLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(disconnectBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(serviceLb)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLb)
                .addGap(18, 18, 18)
                .addComponent(serviceLb)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disconnectBtn)
                    .addComponent(profilePictLb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        portalLb.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        portalLb.setForeground(new java.awt.Color(255, 255, 255));
        portalLb.setText("VISITE");

        profilePictLb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/left_arrow.png"))); // NOI18N
        profilePictLb1.setBorder(null);
        profilePictLb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePictLb1MouseEntered(evt);
            }
        });
        profilePictLb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePictLb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(profilePictLb1)
                .addGap(30, 30, 30)
                .addComponent(portalLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 678, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(profilePictLb1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(portalLb)
                .addGap(40, 40, 40))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 58, 105));
        jLabel3.setText("Nom :");

        nomPatientLbl.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        nomPatientLbl.setForeground(new java.awt.Color(116, 116, 116));

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 58, 105));
        jLabel5.setText("Prénom :");

        prenomPatientLbl.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        prenomPatientLbl.setForeground(new java.awt.Color(116, 116, 116));

        sexeLbl.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        sexeLbl.setForeground(new java.awt.Color(116, 116, 116));

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 58, 105));
        jLabel8.setText("Sexe :");

        dateNaissanceLbl.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        dateNaissanceLbl.setForeground(new java.awt.Color(116, 116, 116));

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 58, 105));
        jLabel10.setText("Date de naissance :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(prenomPatientLbl))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nomPatientLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(dateNaissanceLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(sexeLbl)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nomPatientLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(prenomPatientLbl)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(dateNaissanceLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(sexeLbl))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(31, 28, 105), 2, true));
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N

        lblTypeVisite.setBackground(new java.awt.Color(255, 255, 255));
        lblTypeVisite.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        lblTypeVisite.setForeground(new java.awt.Color(31, 58, 105));
        lblTypeVisite.setText("Consultation");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(31, 58, 105));
        jLabel12.setText("Date :");

        profilePictLb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icone_perso.png"))); // NOI18N
        profilePictLb3.setBorder(null);
        profilePictLb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePictLb3MouseEntered(evt);
            }
        });
        profilePictLb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePictLb3ActionPerformed(evt);
            }
        });

        lblDateConsultation.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblDateConsultation.setForeground(new java.awt.Color(116, 116, 116));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(31, 58, 105));
        jLabel27.setText("Praticien : ");

        lblNomPraticien.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblNomPraticien.setForeground(new java.awt.Color(116, 116, 116));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(31, 58, 105));
        jLabel31.setText("Motif :");

        lblMotif.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblMotif.setForeground(new java.awt.Color(116, 116, 116));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(31, 58, 105));
        jLabel13.setText("Observations");

        profilePictLb4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icone_perso.png"))); // NOI18N
        profilePictLb4.setBorder(null);
        profilePictLb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePictLb4MouseEntered(evt);
            }
        });
        profilePictLb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePictLb4ActionPerformed(evt);
            }
        });

        scrollPaneObs.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneObs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtObservations.setEditable(false);
        txtObservations.setBackground(new java.awt.Color(255, 255, 255));
        txtObservations.setColumns(20);
        txtObservations.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        txtObservations.setForeground(new java.awt.Color(116, 116, 116));
        txtObservations.setLineWrap(true);
        txtObservations.setRows(5);
        txtObservations.setMargin(new java.awt.Insets(5, 5, 5, 5));
        scrollPaneObs.setViewportView(txtObservations);

        profilePictLb5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icone_perso.png"))); // NOI18N
        profilePictLb5.setBorder(null);
        profilePictLb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePictLb5MouseEntered(evt);
            }
        });
        profilePictLb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePictLb5ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(31, 58, 105));
        jLabel14.setText("Prescriptions");

        profilePictLb6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/icone_perso.png"))); // NOI18N
        profilePictLb6.setBorder(null);
        profilePictLb6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilePictLb6MouseEntered(evt);
            }
        });
        profilePictLb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePictLb6ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(31, 58, 105));
        jLabel15.setText("Prestations");

        scrollPanePrescription.setBorder(null);

        prescriptionTable.setBackground(new java.awt.Color(255, 255, 255));
        prescriptionTable.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        prescriptionTable.setForeground(new java.awt.Color(116, 116, 116));
        prescriptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Médicament", "Dose", "Posologie", "Début", "Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prescriptionTable.setEnabled(false);
        prescriptionTable.setFocusable(false);
        prescriptionTable.setGridColor(new java.awt.Color(255, 255, 255));
        prescriptionTable.setRowHeight(40);
        prescriptionTable.setRowMargin(5);
        prescriptionTable.setRowSelectionAllowed(false);
        prescriptionTable.setShowHorizontalLines(false);
        prescriptionTable.setShowVerticalLines(false);
        scrollPanePrescription.setViewportView(prescriptionTable);

        scrollPanePrestation.setBorder(null);

        prestationTable.setBackground(new java.awt.Color(255, 255, 255));
        prestationTable.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        prestationTable.setForeground(new java.awt.Color(116, 116, 116));
        prestationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Médicament", "Dose", "Posologie", "Début", "Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        prestationTable.setEnabled(false);
        prestationTable.setFocusable(false);
        prestationTable.setGridColor(new java.awt.Color(255, 255, 255));
        prestationTable.setRowHeight(40);
        prestationTable.setRowMargin(5);
        prestationTable.setRowSelectionAllowed(false);
        prestationTable.setShowHorizontalLines(false);
        prestationTable.setShowVerticalLines(false);
        scrollPanePrestation.setViewportView(prestationTable);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(31, 58, 105));
        jLabel17.setText("Heure :");

        lblHeureConsultation.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblHeureConsultation.setForeground(new java.awt.Color(116, 116, 116));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(profilePictLb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTypeVisite, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDateConsultation)
                                        .addGap(125, 125, 125)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblHeureConsultation)))
                                .addContainerGap(1768, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNomPraticien))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMotif)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(profilePictLb6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPanePrescription)
                                    .addComponent(scrollPanePrestation)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(profilePictLb5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(profilePictLb4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPaneObs, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 1135, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTypeVisite))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profilePictLb3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(lblHeureConsultation))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(lblDateConsultation)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblNomPraticien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(lblMotif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13))
                    .addComponent(profilePictLb4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneObs, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14))
                    .addComponent(profilePictLb5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPanePrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePictLb6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addComponent(scrollPanePrestation, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        scrollPane.setViewportView(jPanel3);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profilePictLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePictLbActionPerformed

        
    }//GEN-LAST:event_profilePictLbActionPerformed

    private void profilePictLbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictLbMouseEntered
        this.profilePictLb.setBackground(Color.yellow);
    }//GEN-LAST:event_profilePictLbMouseEntered

    private void disconnectBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disconnectBtnMouseEntered
        
    }//GEN-LAST:event_disconnectBtnMouseEntered

    private void disconnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectBtnActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
        this.dispose();
    }//GEN-LAST:event_disconnectBtnActionPerformed

    private void profilePictLb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictLb1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb1MouseEntered

    private void profilePictLb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePictLb1ActionPerformed
        dispose();
    }//GEN-LAST:event_profilePictLb1ActionPerformed

    private void profilePictLb3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictLb3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb3MouseEntered

    private void profilePictLb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePictLb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb3ActionPerformed

    private void profilePictLb4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictLb4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb4MouseEntered

    private void profilePictLb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePictLb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb4ActionPerformed

    private void profilePictLb5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictLb5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb5MouseEntered

    private void profilePictLb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePictLb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb5ActionPerformed

    private void profilePictLb6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilePictLb6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb6MouseEntered

    private void profilePictLb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePictLb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilePictLb6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateNaissanceLbl;
    private javax.swing.JButton disconnectBtn;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblDateConsultation;
    private javax.swing.JLabel lblHeureConsultation;
    private javax.swing.JLabel lblMotif;
    private javax.swing.JLabel lblNomPraticien;
    private javax.swing.JLabel lblTypeVisite;
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel nomPatientLbl;
    private javax.swing.JLabel portalLb;
    private javax.swing.JLabel prenomPatientLbl;
    private javax.swing.JTable prescriptionTable;
    private javax.swing.JTable prestationTable;
    private javax.swing.JButton profilePictLb;
    private javax.swing.JButton profilePictLb1;
    private javax.swing.JButton profilePictLb3;
    private javax.swing.JButton profilePictLb4;
    private javax.swing.JButton profilePictLb5;
    private javax.swing.JButton profilePictLb6;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPaneObs;
    private javax.swing.JScrollPane scrollPanePrescription;
    private javax.swing.JScrollPane scrollPanePrestation;
    private javax.swing.JLabel serviceLb;
    private javax.swing.JLabel sexeLbl;
    private javax.swing.JTextArea txtObservations;
    // End of variables declaration//GEN-END:variables
}
